# Generated by Django 4.0.6 on 2022-07-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contactmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carusel_image', models.ImageField(upload_to='carusel/', verbose_name='carusel_image')),
                ('carusel_text', models.CharField(max_length=100, verbose_name='carusel_text')),
                ('carusel_title', models.CharField(max_length=100, verbose_name='carusel_title')),
                ('carusel_body', models.TextField(verbose_name='carusel_body')),
            ],
            options={
                'verbose_name': 'carusel',
                'verbose_name_plural': 'carusels',
            },
        ),
    ]
